version: "3.3"
services:
  app:
    build:
      args:
        user: leonardo
        uid: 1000
      context: ./docker
      dockerfile: Dockerfile
    image: cd-app
    container_name: cm-webapp
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cdnetwork
  db:
    image: mysql:8.0
    container_name: cm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cddatabase
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_PASSWORD: 12345678
      MYSQL_USER: leonardo
    ports:
      - 3307:3306
    volumes:
      - cdvolumes-db-data:/var/lib/mysql
    networks:
      - cdnetwork
  nginx:
    image: nginx:1.19-alpine
    container_name: cm-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - cdnetwork
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - cdnetwork
volumes:
  cdvolumes-db-data:
networks:
  cdnetwork:
    driver: bridge
